name: CI

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: ["*/*"]
  pull_request:

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: .pre-commit-config.yaml
      - uses: asdf-vm/actions/install@v2.2.0
      - uses: pre-commit/action@v3.0.0
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'yarn'
      - run: yarn install
      - run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      - run: yarn test
